apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdata-flightsql-datasource
    access: proxy
    basicAuth: false
    jsonData:
      host: "influxdb:8181"
      secure: false
      token: "tokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentokentoken"
