apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdata-flightsql-datasource
    access: proxy
    basicAuth: false
    jsonData:
      host: "influxdb:8082"
      secure: false
      token: "my-super-secret-token-change-me"
