apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://idm-influxdb:8086
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: idm
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token-change-me
    isDefault: true
    editable: true
