apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://idm-influxdb:8181
    jsonData:
      version: SQL
      dbName: idm
      httpMode: POST
      defaultBucket: idm
      organization: idm
      tlsSkipVerify: false
    secureJsonData:
      token: apiv3_my-super-secret-token-change-me
    isDefault: true
    editable: true
